export const products = [
  {
    id: 1,
    name: "Cannolo Siciliano",
    description:
      "Il cannolo siciliano tradizionale è fatto con una cialda fritta a forma di tubo ripiena di ricotta di pecora, ma la farcitura può essere varia: dalla crema pasticciera alla chantilly, dalla ricotta di bufala alla crema di pistacchio al cioccolato.",
    price: 2.0,
    category: "Dolci",
    img: "https://media.gettyimages.com/id/86058759/it/foto/stacked-cannoli.jpg?s=2048x2048&w=gi&k=20&c=6XlbROKZiWL_n6ghw6c5N7Dco95kImW7f2bh3k7wOtU=",
    availableInStock: 100,
    nutritionFacts: {
      calories: "320 kcal",
      carbs: "45",
      fat: "18",
      protein: "6",
      sugar: "22",
    },
  },
  {
    id: 2,
    name: "Arancina",
    description:
      "L’arancina è una specialità siciliana a base di riso, ripiena di ragù, piselli e mozzarella, poi impanata e fritta, simbolo della cucina di strada.",
    price: 2.0,
    category: "Street Food",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733340284/SICILIAN-TASTE-SERVER-UPLOADS/arancina.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "250 kcal",
      carbs: "35",
      fat: "9",
      protein: "8",
      sugar: "2",
    },
  },
  {
    id: 3,
    name: "Caponata Siciliana",
    description:
      "La caponata è un piatto siciliano a base di melanzane, pomodori, sedano, olive e capperi, il tutto condito con una salsa agrodolce.",
    price: 4.0,
    category: "Antipasti",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733340945/SICILIAN-TASTE-SERVER-UPLOADS/Caponata-siciliana.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "130 kcal",
      carbs: "18",
      fat: "8",
      protein: "2",
      sugar: "12",
    },
  },
  {
    id: 4,
    name: "Torta Setteveli",
    description:
      "Un dolce siciliano composto da sette strati: pan di spagna, crema gianduia, crema al cioccolato e nocciole, decorato con cioccolato fondente.",
    price: 12.5,
    category: "Dolci",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733353693/SICILIAN-TASTE-SERVER-UPLOADS/torta-setteveli.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "400 kcal",
      carbs: "50",
      fat: "22",
      protein: "6",
      sugar: "40",
    },
  },
  {
    id: 5,
    name: "Caciocavallo Ragusano",
    description:
      "Il Caciocavallo Ragusano è un formaggio a pasta filata, originario della zona di Ragusa. Ha una consistenza elastica e un sapore delicato ma deciso, che diventa più intenso con la stagionatura.",
    price: 9.9,
    category: "Formaggi",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733741238/SICILIAN-TASTE-SERVER-UPLOADS/ragusano-dop.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "320 kcal",
      carbs: "0",
      fat: "26",
      protein: "22",
      sugar: "0",
    },
  },
  {
    id: 6,
    name: "Pane Ca' Meusa",
    description:
      "Panino tipico palermitano a base di polmone e milza di vitello, servito schiettu o maritatu con ricotta, secondo latradizione locale.",
    price: 2.5,
    category: "Street Food",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733338319/SICILIAN-TASTE-SERVER-UPLOADS/panini-ca-meusa.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "230 kcal",
      carbs: "22",
      fat: "12",
      protein: "10",
      sugar: "5",
    },
  },
  {
    id: 7,
    name: "Granita al Limone",
    description:
      "Una delle granite siciliane più amate, fresca e acidula, preparata con limoni freschi.",
    price: 2.8,
    category: "Dolci",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733353541/SICILIAN-TASTE-SERVER-UPLOADS/Granita_al_limone.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "120 kcal",
      carbs: "30",
      fat: "0",
      protein: "0",
      sugar: "28",
    },
  },
  {
    id: 8,
    name: "Tuma",
    description:
      "La Tuma è un formaggio fresco siciliano, dal sapore delicato e leggermente acidulo. Viene preparata con latte di pecora, ma può essere prodotta anche con latte di mucca o capra.",
    price: 7.5,
    category: "Formaggi",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733741755/SICILIAN-TASTE-SERVER-UPLOADS/tumapersa.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "250 kcal",
      carbs: "2",
      fat: "20",
      protein: "18",
      sugar: "1",
    },
  },
  {
    id: 9,
    name: "Ricotta Siciliana",
    description:
      "La ricotta siciliana è un formaggio fresco, morbido e cremoso, prodotto con il siero di latte di pecora o di mucca. È un ingrediente essenziale nella cucina siciliana, usato sia nei piatti salati che in quelli dolci.",
    price: 8.2,
    category: "Formaggi",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733741644/SICILIAN-TASTE-SERVER-UPLOADS/ricotta.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "170 kcal",
      carbs: "2",
      fat: "14",
      protein: "9",
      sugar: "1",
    },
  },
  {
    id: 10,
    name: "Olio Extravergine di Oliva Nocellara del Belice",
    description:
      "L'olio extravergine di oliva Nocellara del Belice è prodotto con la famosa varietà di olive Nocellara, tipica della zona occidentale della Sicilia. Questo olio ha un sapore fruttato, con una leggera nota di amaro e piccante.",
    price: 28.99,
    category: "Olio",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733349940/SICILIAN-TASTE-SERVER-UPLOADS/Olio-Extravergine-di-Oliva-Nocellara-del-Belice.avif",
    availableInStock: 100,
    nutritionFacts: {
      calories: "900 kcal",
      carbs: "0",
      fat: "100",
      protein: "0",
      sugar: "0",
    },
  },
  {
    id: 11,
    name: "Olio Extravergine di Oliva Biancolilla",
    description:
      "L'olio Biancolilla è un olio extravergine di oliva prodotto con l'omonima varietà di olive, prevalentemente coltivate nella zona centrale della Sicilia. Ha un sapore delicato, con leggere note fruttate e un gusto morbido.",
    price: 23.99,
    category: "Olio",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733350676/SICILIAN-TASTE-SERVER-UPLOADS/biancolilla.png",
    availableInStock: 100,
    nutritionFacts: {
      calories: "880 kcal",
      carbs: "0",
      fat: "100",
      protein: "0",
      sugar: "0",
    },
  },
  {
    id: 12,
    name: "Pomodori Secchi",
    description:
      "I pomodori secchi sono una prelibatezza siciliana, conservati sotto sale o olio d'oliva. Vengono essiccati al sole e possono essere usati come ingrediente in insalate, pasta, o come antipasto.",
    price: 7.9,
    category: "Conserve",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733746753/SICILIAN-TASTE-SERVER-UPLOADS/pomodori-secchi.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "220 kcal",
      carbs: "46",
      fat: "1",
      protein: "7",
      sugar: "35",
    },
  },
  {
    id: 13,
    name: "Salsa di Peperoncino",
    description:
      "La salsa di peperoncino siciliana è una conserva piccante fatta con peperoncini freschi, aglio, olio d'oliva, sale e aceto. È un condimento versatile che si abbina a piatti di pasta, carne o pesce.",
    price: 7.8,
    category: "Conserve",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733746861/SICILIAN-TASTE-SERVER-UPLOADS/crema_al_peperoncino.webp",
    availableInStock: 100,
    nutritionFacts: {
      calories: "150 kcal",
      carbs: "5",
      fat: "14",
      protein: "1",
      sugar: "1",
    },
  },
  {
    id: 14,
    name: "Granita ai Gelsi",
    description:
      "Una granita siciliana dal sapore dolce e fruttato, preparata con gelsi freschi, tipica delle zone siciliane dove i gelsi sono coltivati.",
    price: 2.5,
    category: "Dolci",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733353216/SICILIAN-TASTE-SERVER-UPLOADS/granita-di-gelsi.webp",
    availableInStock: 100,
    nutritionFacts: {
      calories: "150 kcal",
      carbs: "35",
      fat: "1",
      protein: "2",
      sugar: "30",
    },
  },
  {
    id: 15,
    name: "Granita al Pistacchio",
    description:
      "Granita siciliana a base di pistacchi, dal sapore ricco e avvolgente.",
    price: 2.5,
    category: "Dolci",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733352962/SICILIAN-TASTE-SERVER-UPLOADS/granita-siciliana-pistacchio-Bronte.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "200 kcal",
      carbs: "28",
      fat: "10",
      protein: "3",
      sugar: "22",
    },
  },
];
