export const products = [
  {
    id: 1,
    name: "Cannolo Siciliano",
    description:
      "Il cannolo siciliano tradizionale è fatto con una cialda fritta a forma di tubo ripiena di ricotta di pecora, ma la farcitura può essere varia: dalla crema pasticciera alla chantilly, dalla ricotta di bufala alla crema di pistacchio al cioccolato.",
    price: 2.0,
    category: "Dolci",
    img: "https://media.gettyimages.com/id/86058759/it/foto/stacked-cannoli.jpg?s=2048x2048&w=gi&k=20&c=6XlbROKZiWL_n6ghw6c5N7Dco95kImW7f2bh3k7wOtU=",
    availableInStock: 100,
    nutritionFacts: {
      calories: "320 kcal",
      carbs: "45",
      fat: "18",
      protein: "6",
      sugar: "22",
    },
  },
  {
    id: 2,
    name: "Arancina",
    description:
      "L’arancina è una specialità siciliana a base di riso, ripiena di ragù, piselli e mozzarella, poi impanata e fritta, simbolo della cucina di strada.",
    price: 2.0,
    category: "Street Food",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733340284/SICILIAN-TASTE-SERVER-UPLOADS/arancina.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "250 kcal",
      carbs: "35",
      fat: "9",
      protein: "8",
      sugar: "2",
    },
  },
  {
    id: 3,
    name: "Caponata Siciliana",
    description:
      "La caponata è un piatto siciliano a base di melanzane, pomodori, sedano, olive e capperi, il tutto condito con una salsa agrodolce.",
    price: 4.0,
    category: "Antipasti",
    img: "https://media.gettyimages.com/id/537423531/it/foto/caponata.jpg?s=2048x2048&w=gi&k=20&c=9NEkRDZGeBRchx0d3c88Jv2FpQOU4OYcHdA2EzyGy_U=",
    availableInStock: 100,
    nutritionFacts: {
      calories: "130 kcal",
      carbs: "18",
      fat: "8",
      protein: "2",
      sugar: "12",
    },
  },
  {
    id: 4,
    name: "Torta Setteveli",
    description:
      "Un dolce siciliano composto da sette strati: pan di spagna, crema gianduia, crema al cioccolato e nocciole, decorato con cioccolato fondente.",
    price: 12.5,
    category: "Dolci",
    img: "https://media.gettyimages.com/id/1366997767/it/foto/torta-setteveli.jpg?s=2048x2048&w=gi&k=20&c=glS6PpQTSYHGwYv6qR5Cjsk0y9o9FksvQIdVscY-mFQ=",
    availableInStock: 100,
    nutritionFacts: {
      calories: "400 kcal",
      carbs: "50",
      fat: "22",
      protein: "6",
      sugar: "40",
    },
  },
  {
    id: 5,
    name: "Caciocavallo Ragusano DOP",
    description: "",
    price: 9.9,
    category: "Formaggi",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733741238/SICILIAN-TASTE-SERVER-UPLOADS/ragusano-dop.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 6,
    name: "Pane Ca' Meusa",
    description:
      "Panino tipico palermitano a base di polmone e milza di vitello, servito schiettu o maritatu con ricotta, secondo latradizione locale.",
    price: 2.5,
    category: "Street Food",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733338319/SICILIAN-TASTE-SERVER-UPLOADS/panini-ca-meusa.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "230 kcal",
      carbs: "22",
      fat: "12",
      protein: "10",
      sugar: "5",
    },
  },
  {
    id: 7,
    name: "Granita al Limone",
    description:
      "Una delle granite siciliane più amate, fresca e acidula, preparata con limoni freschi.",
    price: 2.8,
    category: "Dolci",
    img: "img/cipolla-giarratana.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "120 kcal",
      carbs: "30",
      fat: "0",
      protein: "0",
      sugar: "28",
    },
  },
  {
    id: 8,
    name: "Tuma",
    description:
      "La Tuma è un formaggio fresco siciliano, dal sapore delicato e leggermente acidulo. Viene preparata con latte di pecora, ma può essere prodotta anche con latte di mucca o capra.",
    price: 7.5,
    category: "Formaggi",
    img: "img/pistacchio-bronte.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "250 kcal",
      carbs: "2",
      fat: "20",
      protein: "18",
      sugar: "1",
    },
  },
  {
    id: 9,
    name: "Ricotta Siciliana",
    description:
      "La ricotta siciliana è un formaggio fresco, morbido e cremoso, prodotto con il siero di latte di pecora o di mucca. È un ingrediente essenziale nella cucina siciliana, usato sia nei piatti salati che in quelli dolci.",
    price: 8.2,
    category: "Formaggi",
    img: "img/pane-nero-castelvetrano.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: "170 kcal",
      carbs: "2",
      fat: "14",
      protein: "9",
      sugar: "1",
    },
  },
  {
    id: 10,
    name: "Olio Extravergine di Oliva Nocellara del Belice",
    description:
      "L'olio extravergine di oliva Nocellara del Belice è prodotto con la famosa varietà di olive Nocellara, tipica della zona occidentale della Sicilia. Questo olio ha un sapore fruttato, con una leggera nota di amaro e piccante.",
    price: 28.99,
    category: "Olio",
    img: "https://res.cloudinary.com/dbxysr1a6/image/upload/v1733349940/SICILIAN-TASTE-SERVER-UPLOADS/Olio-Extravergine-di-Oliva-Nocellara-del-Belice.avif",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 11,
    name: "Manna delle Madonie",
    description: "",
    price: 11.9,
    category: "Dolci",
    img: "img/manna-madonie.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 12,
    name: "Cappero di Pantelleria",
    description: "",
    price: 5.7,
    category: "Sottaceti",
    img: "img/capperi-pantelleria.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 13,
    name: "Sale Marino di Trapani",
    description: "",
    price: 1.8,
    category: "Spezie",
    img: "img/sale-trapani.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 14,
    name: "Oliva di Sant’Agostino",
    description: "",
    price: 4.2,
    category: "Olive",
    img: "img/oliva-sant-agostino.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 15,
    name: "Bottarga di Muggine di Trapani",
    description: "",
    price: 14.5,
    category: "Pesce",
    img: "img/bottarga-trapani.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
];
