export const products = [
  {
    id: 1,
    name: "Pomodoro Siccagno della Valle del Belìce",
    description: "",
    price: 4.5,
    category: "Ortaggi",
    img: "img/pomodoro-siccagno.jpg",
    availableInStock: 100,
    nutritionFacts: {
      calories: 0,
      carbs: 0,
      fat: 0,
      protein: 0,
      sugar: 0,
    },
  },
  {
    id: 2,
    name: "Mandorla di Noto",
    description: "",
    price: 6.9,
    category: "Frutta secca",
    img: "img/mandorla-noto.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 3,
    name: "Fava Cottoia Modicana",
    description: "",
    price: 3.8,
    category: "Legumi",
    img: "img/fava-modicana.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 4,
    name: "Suino Nero dei Nebrodi – Salame",
    description: "",
    price: 12.5,
    category: "Salumi",
    img: "img/suino-nero-salame.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 5,
    name: "Caciocavallo Ragusano DOP",
    description: "",
    price: 9.9,
    category: "Formaggi",
    img: "img/ragusano.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 6,
    name: "Provola dei Nebrodi",
    description: "",
    price: 8.5,
    category: "Formaggi",
    img: "img/provola-nebrodi.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 7,
    name: "Cipolla di Giarratana",
    description: "",
    price: 2.8,
    category: "Ortaggi",
    img: "img/cipolla-giarratana.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 8,
    name: "Pistacchio di Bronte",
    description: "",
    price: 7.5,
    category: "Frutta secca",
    img: "img/pistacchio-bronte.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 9,
    name: "Pane Nero di Castelvetrano",
    description: "",
    price: 3.2,
    category: "Pane",
    img: "img/pane-nero-castelvetrano.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 10,
    name: "Arancia Ribera DOP",
    description: "",
    price: 2.9,
    category: "Frutta",
    img: "img/arancia-ribera.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 11,
    name: "Manna delle Madonie",
    description: "",
    price: 11.9,
    category: "Dolci",
    img: "img/manna-madonie.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 12,
    name: "Cappero di Pantelleria",
    description: "",
    price: 5.7,
    category: "Sottaceti",
    img: "img/capperi-pantelleria.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 13,
    name: "Sale Marino di Trapani",
    description: "",
    price: 1.8,
    category: "Spezie",
    img: "img/sale-trapani.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 14,
    name: "Oliva di Sant’Agostino",
    description: "",
    price: 4.2,
    category: "Olive",
    img: "img/oliva-sant-agostino.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
  {
    id: 15,
    name: "Bottarga di Muggine di Trapani",
    description: "",
    price: 14.5,
    category: "Pesce",
    img: "img/bottarga-trapani.jpg",
    availableInStock: 100,
    nutritionFacts: { calories: 0, carbs: 0, fat: 0, protein: 0, sugar: 0 },
  },
];
